export const SIMPLE_ACTION = 'SIMPLE_ACTION';
export const SUBMIT_USER = 'SUBMIT_USER';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';




//user stuff
// export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
// export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';


// //register stuff
// export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
// export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
// export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';

// //ordering stuff
// export const GET_MENU_ITEMS_SUCCESS = 'GET_MENU_ITEMS_SUCCESS';
// export const GET_MENU_ITEMS_FAILED = 'GET_MENU_ITEMS_FAILED';
// export const GET_MENU_ITEMS_REQUEST = 'GET_MENU_ITEMS_REQUEST';

// export const ADD_TO_ORDER = 'ADD_TO_ORDER';
// export const REMOVE_FROM_ORDER = 'REMOVE_FROM_ORDER';

// export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
// export const SEND_ORDER_FAILED = 'SEND_ORDER_FAILED';
// export const SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST';

// Admin Actions
// ADMIN_UPDATE_MENU_SUCCESS = 'ADMIN_UPDATE_MENU_SUCCESS';
// ADMIN_UPDATE_MENU_FAILED = 'ADMIN_UPDATE_MENU_FAILED';
// ADMIN_UPDATE_MENU_REQUEST = 'ADMIN_UPDATE_MENU_REQUEST';

// ADMIN_PRINT_REPORT_SUCCESS = 'ADMIN_PRINT_REPORT_SUCCESS'; 
// ADMIN_PRINT_REPORT_FAILED = 'ADMIN_PRINT_REPORT_FAILED';
// ADMIN_PRINT_REPORT_REQUEST = 'ADMIN_PRINT_REPORT_REQUEST';

//Settings Actions
export const UPDATE_USER = 'UPDATE_USER';
// export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
// export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
// export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';


//Alerts
export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_CLEAR = 'ALERT_CLEAR';



